platform:
- x86
- x64
version: 1.0.{build}
os: Visual Studio 2015
build_script:
- '@echo off'
- setlocal
- ps: >-
    If ($env:Platform -Match "x86") {
      $env:VCVARS_PLATFORM="x86"
    } Else {
      $env:VCVARS_PLATFORM="amd64"
    }
    ren 'C:\Program Files (x86)\Windows Kits\10\include\wdf' '00wdf'
- call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %VCVARS_PLATFORM%
- call build_examples.bat
- exit /b 0
